# attempts to find common Bigrams

decypher_words1 = ["analysis", 'approach', "area", "assessment", "assume", 'authority', 'available', 'benefit',
                   'concept',
                   'consistent', 'constitutional', 'context', 'contract', 'create', 'data', 'definition', 'derived',
                   'distribution', 'economic', 'environment', 'established', 'estimate', 'evidence', 'export',
                   'factors',
                   'financial', 'formula', 'function', 'identified', 'income', 'indicate', 'individual',
                   'interpretation',
                   'involved', 'issues', 'labour', 'legal', 'legislation', 'major', 'method', 'occur', 'percent',
                   'period',
                   'policy', 'principle', 'procedure', 'process', 'required', 'research', 'response', 'role', 'section',
                   'sector',
                   'significant', 'similar', 'source', 'specific', 'structure', 'theory', 'variables']

decypher_words2 = ["achieve", 'acquisition', 'administration', 'affect', 'appropriate', 'aspects', 'assistance',
                   'categories', 'chapter',
                   'commission', 'community', 'complex', 'computer', 'conclusion', 'conduct', 'consequences',
                   'construction', 'consumer', 'credit', 'cultural',
                   'design', 'distinction', 'elements', 'equation', 'evaluation', 'features',
                   'final', 'focus', 'impact', 'injury', 'institute', 'investment', 'items', 'journal',
                   'maintenance', 'normal', 'obtained', 'participation', 'perceived', 'positive', 'potential',
                   'previous', 'primary', 'purchase', 'range', 'region', 'regulations', 'relevant',
                   'resident', 'resources', 'restricted', 'security', 'sought', 'select', 'site', 'strategies',
                   'survey', 'text', 'traditional', 'transfer']

decypher_words3 = ['alternative', 'circumstances', 'comments', 'compensation', 'components', 'consent', 'considerable',
                   'constant', 'constraints', 'contribution', 'convention', 'coordination', 'core', 'corporate',
                   'corresponding', 'criteria', 'deduction', 'demonstrate', 'document', 'dominant', 'emphasis',
                   'ensure', 'excluded', 'framework', 'funds', 'illustrated', 'immigration', 'implies',
                   'initial', 'instance', 'interaction', 'justification', 'layer', 'link', 'location', 'maximum',
                   'minorities', 'negative',
                   'outcomes', 'partnership', 'philosophy', 'physical', 'proportion', 'published', 'reaction',
                   'registered', 'reliance', 'removed', 'scheme', 'sequence', 'sex', 'shift', 'specified', 'sufficient',
                   'task',
                   'technical', 'techniques', 'technology', 'validity', 'volume']

decypher_words4 = ['access', 'adequate', 'annual', 'apparent', 'approximated', 'attitudes', 'attributed', 'civil',
                   'code', 'commitment', 'communication',
                   'concentration', 'conference', 'contrast', 'cycle', 'debate', 'despite', 'dimensions', 'domestic',
                   'emerged', 'error', 'ethnic', 'goals', 'granted', 'hence',
                   'hypothesis', 'implementation', 'implications', 'imposed', 'integration', 'internal',
                   'investigation', 'job',
                   'label', 'mechanism', 'obvious', 'occupational', 'option', 'output', 'overall', 'parallel',
                   'parameters', 'phase',
                   'predicted', 'principal', 'prior', 'professional', 'project', 'promote', 'regime', 'resolution',
                   'retained', 'series', 'statistics', 'status', 'stress', 'subsequent', 'sum', 'summary', 'undertaken']

common_sentence_starters = ["The", "It", "He", "She", "They", "We", "I", "There", "This", "That", "In", "On", "When",
                            "While",
                            "After", "Before", "Because", "Since", "Although", "As", "If", "So", "But", "And", "Then",
                            "Once", "At", "With", "From"]

common_sentence_openings = [
    "Inconclusion",
    "Forexample",
    "Asaresult",
    "Ontheotherhand",
    "Inaddition",
    "However",
    "Therefore",
    "Tobeginwith",
    "Firstofall",
    "Itisimportanttonotethat",
    "Accordingto",
    "Thereis",
    "Thereare",
    "Thepurposeofthis",
    "Thismeansthat",
    "Onereasonis",
    "Anotherpointis",
    "Infact",
    "Interestingly",
    "Overtime",
    "Duringthe",
    "Whileitmayseem",
    "Despitethis",
    "Although",
    "Becauseofthis"
]

meaningful_words = [
    "freedom", "courage", "knowledge", "justice", "truth", "honesty", "friendship", "creativity", "innovation",
    "adventure", "wisdom", "hope", "change", "growth", "balance",
    "focus", "passion", "respect", "gratitude", "integrity", "compassion", "strength", "vision", "confidence",
    "discipline",
    "empathy", "leadership", "resilience", "imagination", "curiosity"
]

testing = [
    "apple", "banana", "computer", "dream", "elephant",
    "freedom", "garden", "happy", "internet", "jungle",
    "knowledge", "love", "mountain", "nature", "ocean",
    "peace", "question", "river", "sunshine", "tree",
    "universe", "victory", "wisdom", "xylophone", "youth", "zebra"
]

there_words = [
    "there",
    "thereabout",
    "thereabouts",
    "thereafter",
    "thereagainst",
    "thereamong",
    "thereamongst",
    "thereat",
    "therebefore",
    "therebetween",
    "thereby",
    "therefrom",
    "therein",
    "thereinside",
    "thereinto",
    "thereof",
    "thereon",
    "thereto",
    "thereunder",
    "thereuntil",
    "thereupon",
    "therewith",
    "therewithin",
    "thereout",
    "thereafterward",
    "thereafterwards"
]

over_words = [
    "over",
    "overact",
    "overachieve",
    "overactive",
    "overanalyze",
    "overbearing",
    "overboard",
    "overcast",
    "overcharge",
    "overcome",
    "overcompensate",
    "overconfident",
    "overcook",
    "overcrowded",
    "overdo",
    "overdose",
    "overdraft",
    "overeat",
    "overestimate",
    "overexert",
    "overexpose",
    "overflow",
    "overgrown",
    "overhaul",
    "overhead",
    "overheat",
    "overjoyed",
    "overkill",
    "overload",
    "overlook",
    "overnight",
    "overpower",
    "overprotective",
    "overqualified",
    "override",
    "overrule",
    "oversee",
    "overshadow",
    "overshoot",
    "oversight",
    "oversleep",
    "overspend",
    "overstate",
    "overstep",
    "overtake",
    "overtax",
    "overthink",
    "overthrow",
    "overtime",
    "overtired",
    "overtly",
    "overtone",
    "overturn",
    "overuse",
    "overwhelm",
    "overwork",
    "overwrite"
]

pro_words = [
    "pro",
    "proactive",
    "probability",
    "probable",
    "probably",
    "probe",
    "problem",
    "procedure",
    "process",
    "processing",
    "processor",
    "proclaim",
    "proclamation",
    "procrastinate",
    "produce",
    "producer",
    "product",
    "production",
    "productive",
    "productivity",
    "profession",
    "professional",
    "professor",
    "profile",
    "profit",
    "profitable",
    "profound",
    "program",
    "progress",
    "progressive",
    "prohibit",
    "project",
    "projection",
    "promise",
    "promote",
    "promotion",
    "prompt",
    "proof",
    "propaganda",
    "propel",
    "proper",
    "property",
    "proposal",
    "propose",
    "prospect",
    "prosper",
    "prosperity",
    "protect",
    "protection",
    "protein",
    "protest",
    "protocol",
    "prove",
    "provide",
    "provider",
    "province",
    "provision",
    "provoke"
]

at_words = [
    "at",
    "ate",
    "atlas",
    "atom",
    "atone",
    "attract",
    "attraction",
    "attractive",
    "attribute",
    "attend",
    "attention",
    "attentive",
    "attic",
    "attain",
    "attempt",
    "attest",
    "attitude",
    "attorney",
    "attack",
    "attach",
    "attachment",
    "attire",
    "attendance",
    "attendant",
    "atmosphere",
    "atmospheric",
    "atrocity",
    "atrophy",
    "atypical"
]

qu_words = [
    "quadratic",
    "qualities",
    "quantized",
    "quickstep",
    "questions",
    "quivering",
    "quenchers",
    "qualified",
    "quickened",
    "quietness",
    "quickfire",
    "quickdraw",
    "quarreled",
    "quittable",
    "quizzical",
    "quaintest",
    "quadruped",
    "quintuplet",
]

se_words = [
    "searching",
    "seriously",
    "seedlings",
    "seemingly",
    "separator",
    "secretive",
    "sensation",
    "sentencey",
    "seclusion",
    "sectarian",
    "selection",
    "semantics",
    "seminated",
    "sergeanty",
    "seriously",
    "selfishly",
    "separator",
    "semesterly",
    "settlement",
    "severable",
    "seafaring",
    "searchers",
    "sensitize",
]

fun_words = [
    "functions",
    "funerally",
    "furnishes",
    "funiculars",
    "fundamenta",
    "furnished",
    "fundraise",
    "funneling",
    "funloving",
    "fungiforms",
    "funniness",
    "funhouses",
    "fundatory",
]

# Attempts to decode by finding the keyword

nine_letter_words = [
    "advantage", "appliance", "attention", "beautiful", "benchmark",
    "breathing", "chocolate", "committed", "conscious", "delighted",
    "education", "fantastic", "generally", "happiness", "important",
    "injection", "knowledge", "marketing", "notorious", "operation",
    "permanent", "recording", "strategic", "treatment", "treasury",
    "volunteer", "wonderful", "adventure", "agreement", "alignment",
    "alliances", "animating", "authority", "awakening", "beginning",
    "belonging", "blessings", "blueprint", "brilliant", "candidate",
    "celebrate", "certainty", "chivalric", "classroom", "cleverest",
    "colorless", "commodity", "companion", "complaint", "conqueror",
    "creatures", "creatives", "cultivate", "dedicated", "democracy",
    "dependent", "directing", "discovery", "efficacy", "education",
    "emotional", "empowered", "endeavors", "energized", "engineers",
    "exploring", "fairytale", "favorable", "fertility", "finishing",
    "fireplace", "flourish", "foolproof", "fortunate", "framework",
    "friendship", "generates", "generous", "gentleman", "governors",
    "happiness", "heartfelt", "highlight", "honeymoon", "hospitals",
    "illustrate", "imaginary", "important", "informed", "injustice",
    "inspired", "intellect", "inventing", "invincible", "knowledge"
]

nine_letter_the_words = [
    "theatrics",
    "theocracy",
    "theorists",
    "theoremic",
    "therapies",
    "therefore",
    "thereunto",
    "therewith",
    "thermally",
    "thermions",
    "thesaurus",
    "theorized",
    "theorizes",
    "theologue",
    "thermobar"
]

nine_letter_ch_words = [
    "challenge",
    "chronicle",
    "checklist",
    "chipmaker",
    "childhood",
    "chivalric",
    "chromatic",
    "chubbiest",
    "chintzily",
    "chequings"
]

nine_letter_gr_words = [
    "grapefruit",
    "greenback",
    "graphical",
    "grassland",
    "greyhound",
    "grumbling",
    "grounding",
    "grandiose",
    "graceless",
    "gratified",
    "gradually",
    "gravitate",
    "greenroom",
    "grappling",
    "grievance",
    "greenwood",
    "greyliest",
    "grandeurs",
    "griddlers",
    "grizzlies",
    "granitize",
    "groundhog",
    "grubstake",
]

nine_letter_pr_words = [
    "practical",
    "procedure",
    "precision",
    "presuming",
    "prisoners",
    "prankster",
    "preachers",
    "president",
    "priceless",
    "primality",
    "prevented",
    "prejudice",
    "prophetic",
    "prototype",
    "proximity",
    "prismatic",
    "privately",
    "prospects",
    "preflight",
    "prickling",
]
